# Generated by Django 6.0.2 on 2026-06-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('service_name', models.CharField(max_length=200, verbose_name='Service')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₹)')),
                ('gst_rate', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%')], default=18, verbose_name='GST Rate')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('customer_address', models.TextField(blank=True, verbose_name='Customer Address')),
                ('customer_gst', models.CharField(blank=True, max_length=50, verbose_name='Customer GSTIN')),
                ('customer_state', models.CharField(blank=True, max_length=100, verbose_name='Customer State')),
                ('customer_state_code', models.CharField(blank=True, max_length=10, verbose_name='State Code')),
                ('hsn_code', models.CharField(default='998311', max_length=20, verbose_name='HSN / SAC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proforma_invoices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'db_table': 'proforma_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
