# Generated by Django 6.0.5 on 2026-06-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_invoice_options_proformainvoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformainvoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_gst',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_state',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_state_code',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='year',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes / Remarks'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='uploaded_pdf',
            field=models.FileField(blank=True, help_text='Upload a ready-made PDF. If provided it will be sent instead of auto-generating.', null=True, upload_to='invoices/uploaded/%Y/%m/', verbose_name='Upload Existing Invoice (PDF)'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='gst_rate',
            field=models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%')], default=18, verbose_name='GST Rate (%)'),
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('hsn_code', models.CharField(default='998311', max_length=20, verbose_name='HSN / SAC')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₹)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.proformainvoice')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'proforma_invoice_items',
            },
        ),
    ]
