# Generated by Django 6.0.2 on 2026-06-15 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_invoiceitem_quantity_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedocument',
            name='is_downloaded',
            field=models.BooleanField(default=False, verbose_name='Downloaded'),
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
