# Generated by Django 6.0.2 on 2026-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_servicedocument_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedocument',
            name='is_reupload',
            field=models.BooleanField(default=False, verbose_name='Re-uploaded'),
        ),
    ]
