# Generated by Django 6.0.5 on 2026-10-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
